---
title: "BestGLM Modeling"
author: "Rachel Jordan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data preparation for bestGLM

```{r}
#import data
training <- read.csv("Training Data.csv",header=T)
testing <- read.csv("Testing Data.csv", header=T)

#remove X variable which I think got inserted during the test/train split 
require(tidyverse)
training <- training %>% 
  select(-c(X))
testing <- testing %>% 
  select(-c(X))

#change all variables in training set explicitly to either factor or numeric to avoid error message
training$BuildingType <- as.factor(training$BuildingType)
training$PhysicalCondition <- factor(training$PhysicalCondition,
                                          levels=c(1:8),labels=c(1:8))
training$Neighborhood <- as.factor(training$Neighborhood)
training$YearBuilt <- as.numeric(training$YearBuilt)
training$FullBath <- as.numeric(training$FullBath)
training$RatingBath <- factor(training$RatingBath,
                                          levels=c(1:8),labels=c(1:8))
training$HalfBath <- as.numeric(training$HalfBath)
training$Kitchen <- as.numeric(training$Kitchen)
training$TotalFinishedArea <- as.numeric(training$TotalFinishedArea)
training$LandSF <- as.numeric(training$LandSF)
training$LastSalePrice <- as.numeric(training$LastSalePrice)
training$SeasonSold <- as.factor(training$SeasonSold)
training$AirConditioned <- as.factor(training$AirConditioned)
training$FrameShed <- as.numeric(training$FrameShed)
training$MasonAdjustment <- as.numeric(training$MasonAdjustment)
training$MiscSfyi <- as.numeric(training$MiscSfyi)
training$PlasticLinedPool <- as.numeric(training$PlasticLinedPool)
training$PrefabPool <- as.numeric(training$PrefabPool)
training$Canopy <- as.numeric(training$Canopy)
training$MetalShed <- as.numeric(training$MetalShed)
training$DivingBoard <- as.numeric(training$DivingBoard)
training$PoolLadder <- as.numeric(training$PoolLadder)
training$ReinforcedConcreteSF <- as.numeric(training$ReinforcedConcreteSF)
training$GreenHouse <- as.numeric(training$GreenHouse)
training$FiberglassPool <- as.numeric(training$FiberglassPool)
training$PoolLighting <- as.numeric(training$PoolLighting)
training$FrameGarage.1 <- as.numeric(training$FrameGarage.1)
training$AsphaltPaving <- as.numeric(training$AsphaltPaving)
training$Valuation2020 <- as.numeric(training$Valuation2020)
training$Valuation2021 <- as.numeric(training$Valuation2021)
training$Valuation2019 <- as.numeric(training$Valuation2019)
training$XCoordinate <- as.numeric(training$XCoordinate)
training$YCoordinate <- as.numeric(training$YCoordinate)
training$NeighborhoodCluster <- as.factor(training$NeighborhoodCluster)
training$QualityC <- factor(training$QualityC,levels=c("Worse","B","A","AA"),labels= c(1:4))
training$PrimaryWallC <- as.factor(training$PrimaryWallC)
training$Parking <- as.numeric(training$Parking)

#move response variable to the end and rename it y, as required by bestglm function
best_glm_training <- training %>% 
  mutate(y = LastSalePrice) %>% 
  select(-y,-LastSalePrice,-BuildingType,y)
  
#edit testing data as well to match
#change all variables in testing set explicitly to either factor or numeric to avoid error message
testing$BuildingType <- as.factor(testing$BuildingType)
testing$PhysicalCondition <- factor(testing$PhysicalCondition,
                                          levels=c(1:8),labels=c(1:8))
testing$Neighborhood <- as.factor(testing$Neighborhood)
testing$YearBuilt <- as.numeric(testing$YearBuilt)
testing$FullBath <- as.numeric(testing$FullBath)
testing$RatingBath <- factor(testing$RatingBath,
                                          levels=c(1:8),labels=c(1:8))
testing$HalfBath <- as.numeric(testing$HalfBath)
testing$Kitchen <- as.numeric(testing$Kitchen)
testing$TotalFinishedArea <- as.numeric(testing$TotalFinishedArea)
testing$LandSF <- as.numeric(testing$LandSF)
testing$LastSalePrice <- as.numeric(testing$LastSalePrice)
testing$SeasonSold <- as.factor(testing$SeasonSold)
testing$AirConditioned <- as.factor(testing$AirConditioned)
testing$FrameShed <- as.numeric(testing$FrameShed)
testing$MasonAdjustment <- as.numeric(testing$MasonAdjustment)
testing$MiscSfyi <- as.numeric(testing$MiscSfyi)
testing$PlasticLinedPool <- as.numeric(testing$PlasticLinedPool)
testing$PrefabPool <- as.numeric(testing$PrefabPool)
testing$Canopy <- as.numeric(testing$Canopy)
testing$MetalShed <- as.numeric(testing$MetalShed)
testing$DivingBoard <- as.numeric(testing$DivingBoard)
testing$PoolLadder <- as.numeric(testing$PoolLadder)
testing$ReinforcedConcreteSF <- as.numeric(testing$ReinforcedConcreteSF)
testing$GreenHouse <- as.numeric(testing$GreenHouse)
testing$FiberglassPool <- as.numeric(testing$FiberglassPool)
testing$PoolLighting <- as.numeric(testing$PoolLighting)
testing$FrameGarage.1 <- as.numeric(testing$FrameGarage.1)
testing$AsphaltPaving <- as.numeric(testing$AsphaltPaving)
testing$Valuation2020 <- as.numeric(testing$Valuation2020)
testing$Valuation2021 <- as.numeric(testing$Valuation2021)
testing$Valuation2019 <- as.numeric(testing$Valuation2019)
testing$XCoordinate <- as.numeric(testing$XCoordinate)
testing$YCoordinate <- as.numeric(testing$YCoordinate)
testing$NeighborhoodCluster <- as.factor(testing$NeighborhoodCluster)
testing$QualityC <- factor(testing$QualityC,levels=c("Worse","B","A","AA"),labels= c(1:4))
testing$PrimaryWallC <- as.factor(testing$PrimaryWallC)
testing$Parking <- as.numeric(testing$Parking)

#move response variable to the end and rename it y, as required by bestglm function
best_glm_testing <- testing %>% 
  mutate(y = LastSalePrice) %>% 
  select(-y,-LastSalePrice,-BuildingType,y)

```

## Try bestGLM

```{r}
require(bestglm)

#best_glm_model <- bestglm(best_glm_training, family=Gamma(link="log"))
#error message in bestglm -- p has to be <= 15! 

#start removing predictors so you can use bestglm
thinned_bestglm_data <- best_glm_training %>% 
  select(-c(Valuation2020,Valuation2021,Valuation2019,FrameGarage.1,SeasonSold,Neighborhood,MiscSfyi,PrefabPool, Canopy, MetalShed, DivingBoard,GreenHouse,FiberglassPool, PoolLighting, AsphaltPaving, RatingBath, FrameShed, MasonAdjustment,PoolLadder,Kitchen,ReinforcedConcreteSF))

#look at the special features and take out the ones that are less significant when plotted against the response on their own

summary(glm(y ~ FrameShed,data=thinned_bestglm_data,family=Gamma(link="log"))) #leave in
summary(glm(y ~ MasonAdjustment,data=thinned_bestglm_data,family=Gamma(link="log"))) #leave in
summary(glm(y ~ MiscSfyi,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove 
summary(glm(y ~ PlasticLinedPool,data=thinned_bestglm_data,family=Gamma(link="log"))) #leave in
summary(glm(y ~ PrefabPool,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove
summary(glm(y ~ Canopy,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove
summary(glm(y ~ MetalShed,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove
summary(glm(y ~ DivingBoard,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove
summary(glm(y ~ PoolLadder,data=thinned_bestglm_data,family=Gamma(link="log"))) #leave in
summary(glm(y ~ ReinforcedConcreteSF,data=thinned_bestglm_data,family=Gamma(link="log"))) #leave in
summary(glm(y ~ GreenHouse,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove
summary(glm(y ~ FiberglassPool,data=thinned_bestglm_data,family=Gamma(link="log")))
#remove
summary(glm(y ~ PoolLighting,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove
summary(glm(y ~ AsphaltPaving,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove
summary(glm(y ~ FrameShed,data=thinned_bestglm_data,family=Gamma(link="log")))
summary(glm(y ~ Parking,data=thinned_bestglm_data,family=Gamma(link="log"))) #leave in
summary(glm(y ~ QualityC,data=thinned_bestglm_data,family=Gamma(link="log"))) #leave in
summary(glm(y ~ YCoordinate,data=thinned_bestglm_data,family=Gamma(link="log"))) #leave in
summary(glm(y ~ Kitchen,data=thinned_bestglm_data,family=Gamma(link="log"))) #remove
summary(glm(y ~ AirConditioned,data=thinned_bestglm_data,family=Gamma(link="log")))


#try bestglm again
bestglm_model <- bestglm(thinned_bestglm_data,family=Gamma(link="log"))
summary(bestglm_model$BestModel)
#Morgan-Tatar search since family is non-gaussian.
#Note: factors present with more than 2 levels.

#change testing variables to match training variables
#crossvalidate
mean((predict(bestglm_model$BestModel,newdata = best_glm_testing, type="response") - best_glm_testing$y)**2) #MSE is equal to 40,807,050,303. predictions are on the wrong scale. insert type= "response" and you get 2,992,232,474. Better! 

sqrt(2992232474) #we are off by an average amount of $54,701.3

#is a single off prediction messing with the MSE? 
best_glm_predictions <- as.data.frame(predict(bestglm_model$BestModel, newdata = best_glm_testing, type = "response"))
```
