---
title: "Purposeful Variable Selection with Gamma GLM"
author: "Rachel Jordan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data

```{r}
testing <- read.csv("Testing Data.csv",header=T)
training <- read.csv("Training Data.csv",header=T)

```

Step 1: Construct an initial main-effects model using explanatory variables that include the known important variables and others that show any evidence of being relevant when used as sole predictors (e.g., having P-value \< 0.2).

```{r}
summary(glm(LastSalePrice ~ BuildingType,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ factor(PhysicalCondition),data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ factor(Neighborhood),data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ YearBuilt,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ FullBath,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ factor(RatingBath),data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ HalfBath,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ Kitchen,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ TotalFinishedArea,data=training,family=Gamma(link="log"))) #keep

summary(glm(LastSalePrice ~ LandSF,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ AirConditioned,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ FrameShed,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ MasonAdjustment,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ MiscSfyi,data=training,family=Gamma(link="log"))) 
############DROP

summary(glm(LastSalePrice ~ PlasticLinedPool,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ PrefabPool,data=training,family=Gamma(link="log"))) 
############DROP

summary(glm(LastSalePrice ~ Canopy,data=training,family=Gamma(link="log"))) 
############DROP

summary(glm(LastSalePrice ~ MetalShed,data=training,family=Gamma(link="log"))) 
############DROP

summary(glm(LastSalePrice ~ DivingBoard,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ PoolLadder,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ ReinforcedConcreteSF,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ GreenHouse,data=training,family=Gamma(link="log"))) 
############DROP

summary(glm(LastSalePrice ~ FiberglassPool,data=training,family=Gamma(link="log"))) 
############DROP

summary(glm(LastSalePrice ~ PoolLighting,data=training,family=Gamma(link="log"))) 
############DROP

summary(glm(LastSalePrice ~ FrameGarage.1,data=training,family=Gamma(link="log"))) 
###########DROP

summary(glm(LastSalePrice ~ AsphaltPaving,data=training,family=Gamma(link="log"))) 
##########DROP

summary(glm(LastSalePrice ~ Valuation2021,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ XCoordinate,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ YCoordinate,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ factor(NeighborhoodCluster),data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ QualityC,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ PrimaryWallC,data=training,family=Gamma(link="log"))) 
#keep

summary(glm(LastSalePrice ~ Parking,data=training,family=Gamma(link="log"))) 
#keep

```

Test model that results from just keeping the variables that are significant in step 1

```{r}
step1_model <- glm(LastSalePrice ~ factor(PhysicalCondition)  + factor(Neighborhood) + YearBuilt + FullBath + factor(RatingBath) + HalfBath + Kitchen + TotalFinishedArea + LandSF + AirConditioned + FrameShed + MasonAdjustment + PlasticLinedPool + DivingBoard + PoolLadder + ReinforcedConcreteSF + Valuation2021 + XCoordinate + YCoordinate + QualityC + PrimaryWallC + Parking,data=training,family=Gamma(link="log"))

mean((predict(step1_model,newdata=testing,type="response") - testing$LastSalePrice)**2) #2,420,246,419

mean(((predict(step1_model,newdata=testing,type="response") - testing$LastSalePrice)/testing$LastSalePrice)) #just over 11% off for each house

#assessment sales ratio
median((predict(step1_model,newdata=testing,type="response")/testing$LastSalePrice)) #1.05

#remove neighborhood or neighborhoood cluster because they make it rank-deficient and "misleading". using neighborhoodcluster results in a slightly worse model in terms of both sales ratio and COD so use neighborhood

#coefficient of dispersion
sales_ratios_glm <- predict(step1_model,newdata=testing,type="response")/testing$LastSalePrice
require(stats)
median_glm <- median(sales_ratios_glm)
mean((sales_ratios_glm-median_glm)/median_glm) #0.062 < 0.15
```

Trying a linear model

```{r}
linear_model <- lm(LastSalePrice ~ factor(PhysicalCondition) + factor(Neighborhood) + YearBuilt + FullBath + factor(RatingBath) + HalfBath + Kitchen + TotalFinishedArea + LandSF + AirConditioned + FrameShed + MasonAdjustment + PlasticLinedPool + DivingBoard + PoolLadder + ReinforcedConcreteSF + Valuation2021 + XCoordinate + YCoordinate + QualityC + PrimaryWallC + Parking,data=training)

mean((predict(linear_model,newdata = testing) - testing$LastSalePrice)**2) #2,017,051,097

mean(((predict(linear_model,newdata=testing) - testing$LastSalePrice)/testing$LastSalePrice)) #we are just over 10% off on average for each house

#assessment sales ratio
median((predict(linear_model,newdata=testing)/testing$LastSalePrice)) #1.05

#coefficient of dispersion
sales_ratios_lm <- predict(linear_model,newdata=testing)/testing$LastSalePrice
median_lm <- median(sales_ratios_lm)
mean((sales_ratios_lm-median_lm)/median_lm) #0.05 > 0.15

#remove valuation2021
linear_model_2 <- lm(LastSalePrice ~ factor(PhysicalCondition) + factor(Neighborhood) + YearBuilt + FullBath + factor(RatingBath) + HalfBath + Kitchen + TotalFinishedArea + LandSF + AirConditioned + FrameShed + MasonAdjustment + PlasticLinedPool + DivingBoard + PoolLadder + ReinforcedConcreteSF + XCoordinate + YCoordinate + QualityC + PrimaryWallC + Parking,data=training)

#assessment sales ratio
median((predict(linear_model_2,newdata=testing)/testing$LastSalePrice)) #1.04

#coefficient of dispersion
sales_ratios_lm_2 <- predict(linear_model_2,newdata=testing)/testing$LastSalePrice
median_lm_2 <- median(sales_ratios_lm_2)
mean((sales_ratios_lm_2-median_lm_2)/median_lm_2) #0.053 < 0.15
```
